name: aikitchen
description: "Aplicacion de recetas usando la IA de google"
publish_to: "none"
version: 2.5.3+32

environment:
  sdk: ^3.8.0

dependencies:
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  dynamic_color: ^1.6.8
  flutter:
    sdk: flutter
  flutter_inset_shadow: ^2.0.3
  flutter_tts: ^4.2.3
  fluttertoast: ^9.0.0
  google_generative_ai: ^0.4.6
  home_widget: ^0.8.0
  lottie: ^3.1.2
  path_provider: ^2.1.5
  receive_sharing_intent: ^1.4.5
  share_plus: ^12.0.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  http: ^1.2.0
  properties: ^2.1.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/buscando.json
    - assets/guide/step1.jpg
    - assets/guide/step2.jpg
    - assets/guide/step3.jpg
    - assets/guide/step4.jpg
    - assets/guide/step5.jpg
    - assets/guide/step6.jpg
    - config.properties
